ALTER TABLE `realmlist` 
	DROP COLUMN `ra`,
	DROP COLUMN `ra_port`,
	DROP COLUMN `soap`,
	DROP COLUMN `soap_port`,
	DROP COLUMN `char_db`,
	DROP COLUMN `world_db`,
	DROP COLUMN `p_limit`,
	DROP COLUMN `unstuck`,
	DROP COLUMN `teleport`,
	DROP COLUMN `changes`,
	DROP COLUMN `3d_char_preview`,
	DROP COLUMN `unstuck_price`,
	DROP COLUMN `teleport_price`,
	DROP COLUMN `change_faction_price`,
	DROP COLUMN `change_race_price`,
	DROP COLUMN `change_appearance_price`;
	DROP COLUMN `core`;